### ISSUE TITLE
We will need documentation about this one

### ISSUE THREAD

**Issue by vietartisans** [duyngha/vietartisans-library#4]
Hey @duyngha great work man! But we will need documentation for this one. I have installed it in a wordpress site but I have no idea how to use it.

**Comment by duyngha** [comment]
Hi @vietartisans 
I have already created a tut in Vietartisans Tutorials a few days ago. You may want to check this out.
https://www.vietartisans.io/tutorials/huong-dan-su-dung-cac-chuc-nang-cua-plugin-vietartisans-library/
Thanks,

**Comment by vietartisans** [comment]
Yeah and we will need a readme file on github as well. Keep all documentation in markdown format. Then we can easily copy-paste it across platform.

**Comment by duyngha** [comment]
I create repository for VAL plugin under our branch account. From now, we will do anything in here https://github.com/Viet-Artisans/vietartisans-library

**Comment by duyngha** [comment]
Also, can you help me create README file to help people cover understand how it work in english version. I'll write wiki for it shortly.
